language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2

sudo: false

env:
  - COMPOSER_OPTS=""
  - COMPOSER_OPTS="--prefer-lowest"

before_install:
  - mkdir tests/files

install:
  - travis_retry composer update --prefer-dist $COMPOSER_OPTS

script:
  - bin/phpunit --coverage-text --coverage-clover coverage.xml
  - bin/phpspec run

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.xml
